---
title: "Pocillopora_grandis_DvsC"
author: "JK"
date: "2025-03-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(htmltools)
library(arrayQualityMetrics)
library(DESeq2)
library(tidyr)
library(genefilter)
library(cowplot)
library(emmeans)
library(gplots)
library(reshape2)
library(plyr)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(ggtext)
library(ape)
library(vegan)
library(RColorBrewer)
#try combat-seq
library(sva)
#install.packages("readxl")
#install.packages("expss")
library(readxl)
library(expss)
#pullout the data here https://www.nature.com/articles/s41467-023-38610-6#Sec2
```

```{r}
#sample information here
#https://github.com/institut-de-genomique/TaraPacific_Pocillopora-transcriptomic/tree/main/Figure_1
# Set the prefix for each output file name
#samples were mapped to P meandrina genome
#The Pocillopora genome is available at https://www.genoscope.cns.fr/corals/genomes.html

outputPrefix <- "Pocillopora_Figures_2021-10"

############################
##### Load Count Data  #####
#raw gene expression for the host: Pocillopora_MetaT_ReadCount.tab available in this directory or at https://doi.org/10.5281/zenodo.6341761
# Step 1 - Load Pocillopora and Cladocopium raw count file with reads mapped to the predicted coding sequence
cts_raw_poc <- read.table("Pocillopora_MetaT_ReadCount.tab", header=TRUE, com='', sep='\t', row.names=1, check.names=FALSE)
colnames(cts_raw_poc) <- gsub("C0","C",colnames(cts_raw_poc))
#total genes 35,544
# Step 2 - Merge Host and Algae_type read count dataframes by colony
cols_keep <- colnames(cts_raw_poc)
cts_raw <- cts_raw_poc[,cols_keep]
  
# Step 3 - Add coral host clade information from D. Forcioli's SVD tree
Colony <- colnames(cts_raw)
Ile <- substr(Colony, 1, 3)
IleSite <- substr(Colony, 1, 6)
Site <- substr(Colony, 4, 6)

CladeTable <- read_excel("ITS2-Kmeans-clustering_Pocillopora_JL.xlsx", sheet = "RData")

    

Clade <- vlookup(Colony, CladeTable, result_column = "PocilloSVD", lookup_column = "Colony")
IleClade <- paste(substr(unique(Colony), 1, 3), Clade, sep="")
    
#3b - Add Algae_type clade information from metaT-based assignations (G1 - G6)
SymClade <- vlookup(Colony, CladeTable, result_column = "PopMetaT", lookup_column = "Colony")
IleSymClade <- paste(substr(unique(Colony), 1, 3), SymClade, sep="")
Holobiotype <- paste(Clade, SymClade, sep="_")
IleHolobiotype <- paste(Ile, Holobiotype, sep='_')

# Step 4 - Create table containing all pertinent metadata
sampleTable <- data.frame("Colony" = Colony,
                       "Ile" = Ile, "Site" = Site, "IleSite" = IleSite, 
                       "Clade" = Clade, "SymClade" = SymClade, 
                       "Holobiotype" = Holobiotype, "IleHolobiotype" = IleHolobiotype)
#write csv
write.csv(sampleTable, file = paste0(outputPrefix, "_SampleTable.csv"), row.names = FALSE)
```

```{r}
#load clean sample info file with only P grandis information (SVD4). I pick this because this is the only species with eithor D or C ans domonant algae.
pgran<- read.csv("Pgrandis_sample_info.csv", header = TRUE, stringsAsFactors = FALSE)
#then subset the data to only include the samples that are in the sample info file.
# Suppose the sample names in pgran are under a column called "sample_name"
pgran_samples <- pgran$Sample # Adjust this if the column name is different
# Subset cts_raw by keeping only columns present in pgran_samples
cts_pgran <- cts_raw[, colnames(cts_raw) %in% pgran_samples]
#save new counts matrix
write.csv(cts_pgran, file = "Pgrandis_Counts.csv", row.names = TRUE)
```


```{r}
#start DE analysis here
##analyse full matrix
coldata<-read.csv("Pgrandis_sample_info.csv")
#read in counts 
data <- read.csv("Pgrandis_Counts.csv",header = T, row.names = 1)
#total transcript of host 35,544. remove lowly expressed genes. <10 for a lot of samples. I wont include in analysis.
data[data < 0]<- NA
data<- na.omit(data)
min_count <- 10
min_samples <- 10
#use min count 10, 8085 remain 
# Filter genes. remove low counts.
data <- data[rowSums(data >= min_count) >= min_samples, ]
#25402 genes remain
#subset site 1 only
#
site_S01_samples <- coldata$Sample[coldata$Site == "S01"]
#have 15 samples
# Intersect with available columns in data
site_S01_samples <- intersect(site_S01_samples, colnames(data))
# Subset counts matrix
data_S01 <- data[, site_S01_samples]
data=data_S01
#make new coldata
coldata_S01 <- subset(coldata, Site == "S01")
coldata=coldata_S01
```

```{r}
dds<-DESeq2::DESeqDataSetFromMatrix(countData = data, colData = coldata, design=~Algae_type)
keep.corr = rowSums(counts(dds) >= 2) >= 12 # at least 14 samples (80%) with a count of 2 or higher
dds = dds[keep.corr,]
## saving the rlog for DEG heatmap
rlog <- DESeq2::rlog(dds, blind = TRUE) #for use later on
#save text
rlog_matrix <- assay(rlog)
vsd <- varianceStabilizingTransformation(dds, blind = TRUE) # quickly estimate dispersion trend and apply a variance stabilizing transformation
write.table(rlog_matrix, file = "Pgrandis_COrrected_rlog_normalized_counts.txt", sep = "\t", quote = FALSE, col.names = NA)
vsd_matrix <- assay(vsd)
write.table(vsd_matrix, file = "Pgrandis_COrrected_vsd_normalized_counts.txt", sep = "\t", quote = FALSE, col.names = NA)
## Save dds and vsd data 
save(data,dds, vsd, rlog, file = "pgrandis_noncombat_transformed_counts.RData")
```

```{r}
#conduct outlier test to see which samples are outliers
vsd.ge=assay(vst(dds))
rl=vst(dds)
e=ExpressionSet(assay(rl), AnnotatedDataFrame(as.data.frame(colData(rl))))
arrayQualityMetrics(e,outdir="outlier_raw",intgroup=c("Algae_type"),force=T)
# double-click index.html
#all good. no outliers detected for raw counts.
```

```{r unfiltered size factor plots, fig.width = 10, fig.height = 4}
nrow <- nrow(data) # number of rows/counts (25033)
countMat <- DESeqDataSetFromMatrix(data, coldata, ~ 1) # makes a DESeqDataSet object with count data, experimental design, and no design formula
counts_SF <- estimateSizeFactors(countMat) #  estimates the size factors using the "median ratio method" described by Equation 5 in Anders and Huber (2010)

# make dataframe of the size factors to visualize
sizeFactors <- data.frame(sample = counts_SF@colData@listData[["Sample"]], treat = counts_SF@colData@listData[["Algae_type"]], sizeFactors = counts_SF@colData@listData[["sizeFactor"]])
cbPalette <- c(Cladocopium="#2c7fb8", Durusdinium ="#de2d26")
# plot sizeFactors
ggplot(data = sizeFactors, aes(x = sample, y = sizeFactors, fill = treat)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values=cbPalette) +
  #scale_fill_brewer(palette = 2, type = "qual") +
  geom_bar(stat = "identity") +
  ggtitle("Unfiltered sizeFactors")
ggsave("Sizefactor_raw.pdf", width = 4.5, height = 3.5)
```



```{r}
str(coldata)
#Perform PCA on variance-stabilized data (vsd), including "age" as a grouping variable
pcaData <- plotPCA(vsd, intgroup = c("Algae_type","Ile", "Site", "Lib_type"), returnData = TRUE)
# extract variance for all PCs
percentVar <- round((100 * attr(pcaData, "percentVar")), 2)
percentVar
pcaData$Algae_type <- as.factor(pcaData$Algae_type)
pcaData$Ile <- as.factor(pcaData$Ile)
pcaData$Site <- as.factor(pcaData$Site)
pcaData$Lib_type <- as.factor(pcaData$Lib_type)
# Run adonis
GE_pca <-adonis2(pcaData[, 1:2] ~ Algae_type*Lib_type, data = pcaData, method = 'euclidean', permutations = 1500)
GE_pca
#Algae_type  1     2726 0.05231 1.6021 0.22185  
#Lib_type    1     6850 0.13142 4.0251 0.04464 *
#platform bias is showing up. I will run combatseq to remove batch effects of seqeuncing platform.
```

```{r}
##
#shapes = c("B" = 21, "C" = 22, "ECAH"=24,"ECG"=25, "ORAG"=1, "P2"=2, "P3"=3)
colvec<- c(Cladocopium="brown4", Durusdinium ="darkgreen")
#points are overlapping with each other. Use jitter to make each point visible.
pca_plot <- ggplot(pcaData, aes(PC1, PC2, shape = Ile, group = Algae_type, fill = Algae_type, colour = Algae_type)) +
  geom_jitter(size = 1.5, stroke = 0.7, alpha = 0.8, width = 3.5, height = 4.5) + # Add jitter to reduce overlap
  theme_bw() +
  stat_ellipse(geom = "polygon", alpha = 0.15, aes(fill = Algae_type), show.legend = FALSE) + # Keep ellipses behind points
  scale_fill_manual(values = colvec) +
  scale_color_manual(values = colvec) +
  xlab(paste0("PC1 (", percentVar[1], "%)")) +
  ylab(paste0("PC2 (", percentVar[2], "%)")) +
  #scale_shape_manual(values = shapes) +
  theme(legend.position = "right")# +facet_wrap(~Ile, scales = "free_y")
pca_plot
ggsave("PCA_corrected.pdf", width = 4.5, height = 3.5)
```

```{r}
#start batch correction here.
#source of code: https://academic.oup.com/nargab/article/2/3/lqaa078/5909519
#start line 233 in Hannah's script
#https://github.com/hannahaichelman/Oculina_Host_Sym_GE/blob/main/03_DESeq_Scripts/deseq_culturesymcombined.Rmd
## Use ComBat_seq to perform batch correction
# counts is the matrix of gene expression raw counts, converting to a matrix here using as.matrix()
# batch is the batch effect you are worried about (here, whether in culture or in host, because this corresponds to samples being sequenced at different times on different platforms, and with different library prep methods)
# group is the biological treatment of interest(here, Algae_type treatment)
# ComBat-seq needs raw, unnormalized, unlogged counts as an input. Do not apply any rarification before running the batch effects. 
#
corrected_data = ComBat_seq(counts = as.matrix(data), batch = coldata$Lib_type, group = coldata$Algae_type)
## Save dds and vsd data 
save(corrected_data, file = "Pgrandis_kate_transformed_counts.RData")
```


```{r}
#Look at total counts
# Assuming corrected_data and coldata are already loaded and correctly aligned
totalCounts.corr = colSums(corrected_data)

num_colors = length(unique(coldata$Ile))
color_palette = brewer.pal(num_colors, "Set3")

# Mapping each sample to a color
sample_colors = color_palette[as.factor(coldata$Ile)]

# Creating the barplot
barplot(totalCounts.corr, col=sample_colors, ylab="raw counts", main="P grandis - Batch corrected",
        names.arg=colnames(corrected_data))

min(totalCounts.corr)
#45188280
max(totalCounts.corr) 
#96487251
```
```{r}
data=corrected_data
nrow <- nrow(data) # number of rows/counts (38828)
countMat <- DESeqDataSetFromMatrix(data, coldata, ~ 1) # makes a DESeqDataSet object with count data, experimental design, and no design formula
counts_SF <- estimateSizeFactors(countMat) #  estimates the size factors using the "median ratio method" described by Equation 5 in Anders and Huber (2010)

# make dataframe of the size factors to visualize
sizeFactors <- data.frame(sample = counts_SF@colData@listData[["Sample"]], treat = counts_SF@colData@listData[["Algae_type"]], sizeFactors = counts_SF@colData@listData[["sizeFactor"]])
cbPalette <- c(Cladocopium="brown4", Durusdinium ="darkgreen")
# plot sizeFactors
ggplot(data = sizeFactors, aes(x = sample, y = sizeFactors, fill = treat)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values=cbPalette) +
  #scale_fill_brewer(palette = 2, type = "qual") +
  geom_bar(stat = "identity") +
  ggtitle("Combatseq filtered sizeFactors")
ggsave("Sizefactors_TaraOce_batch_corr.pdf", width = 4.5, height = 3.5)
```


```{r}
dds<-DESeq2::DESeqDataSetFromMatrix(countData = corrected_data, colData = coldata, design=~Algae_type)
keep.corr = rowSums(counts(dds) >= 2) >= 12 # at least 23 samples (80%) with a count of 2 or higher
dds = dds[keep.corr,]
dds<-DESeq(dds)
## saving the rlog for DEG heatmap
rlog <- DESeq2::rlog(dds, blind = TRUE) #for use later on
#save text
rlog_matrix <- assay(rlog)
vsd <- varianceStabilizingTransformation(dds, blind = TRUE) # quickly estimate dispersion trend and apply a variance stabilizing transformation
write.table(rlog_matrix, file = "Pgrandis_COrrected_rlog_normalized_counts.txt", sep = "\t", quote = FALSE, col.names = NA)
vsd_matrix <- assay(vsd)
write.table(vsd_matrix, file = "Pgrandis_COrrected_vsd_normalized_counts.txt", sep = "\t", quote = FALSE, col.names = NA)
## Save dds and vsd data 
save(corrected_data,dds, vsd, rlog, file = "pgrandis_corrected_transformed_counts.RData")
```


```{r}
str(coldata)
#Perform PCA on variance-stabilized data (vsd), including "age" as a grouping variable
pcaData <- plotPCA(vsd, intgroup = c("Algae_type","Ile", "Site","Lib_type"), returnData = TRUE)
# extract variance for all PCs
percentVar <- round((100 * attr(pcaData, "percentVar")), 2)
percentVar
pcaData$Algae_type <- as.factor(pcaData$Algae_type)
pcaData$Ile <- as.factor(pcaData$Ile)
pcaData$Site <- as.factor(pcaData$Site)
pcaData$Lib_type <- as.factor(pcaData$Lib_type)
# Run adonis Algae_type and Platform
GE_pca <-adonis2(pcaData[, 1:2] ~ Algae_type*Lib_type, data = pcaData, method = 'euclidean', permutations = 1500)
GE_pca
adonis2(formula = pcaData[, 1:2] ~ Algae_type * Lib_type, data = pcaData, permutations = 1500, method = "euclidean")
#                    Df SumOfSqs      R2       F    Pr(>F)    
#Algae_type           1   8759.4 0.50202 14.1091 0.0006662 ***
#Lib_type             1    474.4 0.02719  0.7642 0.5063291    
#Algae_type:Lib_type  1   1385.2 0.07939  2.2312 0.1419054    
##Residual            11   6829.2 0.39140                      
#Total               14  17448.2 1.00000                      
#---
#Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```


```{r}
##
#shapes = c("B" = 2, "C" = 21, "ECAH"=22,"ECG"=23, "ORAG"=24, "P2"=25, "P3"=8)
colvec<- c(Cladocopium="brown4", Durusdinium ="darkgreen")
#points are overlapping with each other. Use jitter to make each point visible.
pca_plot <- ggplot(pcaData, aes(PC1, PC2, shape = Ile, group = Algae_type, fill = Algae_type, colour = Algae_type)) +
  geom_jitter(size = 2.5, stroke = 0.7, alpha = 0.8) + # Add jitter to reduce overlap
  theme_bw() +
  stat_ellipse(geom = "polygon", alpha = 0.15, aes(fill = Algae_type),level=0.95, show.legend = FALSE) + # Keep ellipses behind points
  scale_fill_manual(values = colvec) +
  scale_color_manual(values = colvec) +
  xlab(paste0("PC1 (", percentVar[1], "%)")) +
  ylab(paste0("PC2 (", percentVar[2], "%)")) +
 # scale_shape_manual(values = shapes) +
  theme(legend.position = "right")#+facet_wrap(~Ile)
pca_plot
ggsave("PCA_pgrandis_batch_corr.pdf", width = 5, height = 3.5)
```


```{r}
#conduct outlier test to see which samples are outliers
vsd.ge=assay(vst(dds))
rl=vst(dds)
e=ExpressionSet(assay(rl), AnnotatedDataFrame(as.data.frame(colData(rl))))
arrayQualityMetrics(e,outdir="outlier",intgroup=c("Algae_type"),force=T)
# double-click index.html
#no outliers detected!
```

```{r Differential gene expression}
#Durisdinium vs Cladocopium pairwise comparisons
coldata$Algae_type<-factor(coldata$Algae_type, levels=c("Durusdinium","Cladocopium"))
#results will be Dur/Cladocopium
dge_Dur <- results(dds, contrast=c("Algae_type","Durusdinium","Cladocopium"))
#check DGE cutoff padj <0.05
table(dge_Dur$padj<0.05)
#FALSE  TRUE 
#22246  2036 
sig_dge_Dur <- dge_Dur[which(dge_Dur$padj < 0.05), ]
summary(sig_dge_Dur)
#adjusted p-value < 0.05
#adjusted p-value < 0.05
#LFC > 0 (up)       : 912, 3.8%
#LFC < 0 (down)     : 1124, 4.6%
dge_Dur_fltd <- dge_Dur[which(dge_Dur$padj<0.05),]
table(dge_Dur_fltd$padj<0.05)
write.table(dge_Dur, file="Pgrandis_dge_Dur.txt", quote=F, sep="\t")
dge_Dur<-read.delim("Pgrandis_dge_Dur.txt",header = TRUE)
dge_Dur_fltd <- dge_Dur[which(dge_Dur$padj<0.05),]
```


```{r}
# Categorize the genes as upregulated or downregulated
# Function to categorize and summarize data
summarize_data <- function(data, label) {
  data$regulation <- ifelse(data$log2FoldChange > 0, "Upregulated", "Downregulated")
  summary_data <- as.data.frame(table(data$regulation))
  colnames(summary_data) <- c("Regulation", "Count")
  summary_data$Dataset <- label
  return(summary_data)
}

# Summarize each data frame
duris <- summarize_data(dge_Dur_fltd, "Heat")
col<-c("Upregulated"="Red","Downregulated"="Blue")
# Create the combined stacked bar plot
ggplot(duris, aes(x = Regulation, y = Count, fill = Regulation)) +
  geom_bar(stat = "identity") +
  theme_classic() +
  labs(x = "Treatment",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_fill_manual(values = col)+coord_flip()+geom_text(aes(label = Count), position = position_stack(vjust = 0.5), color = "white", size=5)
ggsave("DGE_stack_barplot.pdf", width = 4.3, height = 3)
```

```{r}
#prepare data matrix for GOMWU
# Prepare data frame with required transformations
data_dge <- as.data.frame(dge_Dur)
data_dge$Gene<-row.names(data_dge)
data_dge<-read.delim("Pgrandis_dge_Dur.txt", header=TRUE, row.names=1)
# Move row names to a column named 'Gene'
data_dge$Gene <- rownames(data_dge)

# Optionally, make 'Gene' the first column if not already
data_dge <- data_dge[, c("Gene", setdiff(names(data_dge), "Gene"))]
data_dge <- data_dge %>%
  mutate(
    signedlogP = -log10(pvalue) * if_else(log2FoldChange < 0, -1, 1)
  )
# Adjust pvalue based on the sign of log2FoldChange
#gomwu suggest to use "form of "signed negative log p-values". These measures are negative decimal logarithms of the raw (uncorrected) p-value for each gene, multiplied by -1 if the gene was down-regulated. As a result, highly significant up-regulated genes get highly positive values, and highly significant down-regulated genes get highly negative values." from Misha Matz file
data_dge$Spvalue<-log(data_dge$pvalue)
#https://github.com/hrivera28/oculina_heterotrophy/blob/main/Master_analyses_final.R line 949-950
data_dge<-mutate(data_dge,signedlogP=case_when(log2FoldChange<0 ~ Spvalue, log2FoldChange>0 ~ Spvalue*-1))

# Select and rename columns to create the final matrix
dge_matrix_gomwu <- data_dge[, c("Gene", "signedlogP")]
colnames(dge_matrix_gomwu) <- c("Gene", "signedlogP")
dge_matrix_gomwu2<-dge_matrix_gomwu[1:2]
# Remove row names
rownames(dge_matrix_gomwu2) <- NULL
# Set the option to print numbers in standard decimal format
options(scipen = 999)
write.csv(dge_matrix_gomwu2, file="Pgrandis_dge_Dur_gomwu.csv", quote=FALSE,row.names=FALSE)
options(scipen = 0)
```

```{r}
diff_expr_matrix <- data_dge
str(diff_expr_matrix)
volcano_data <- data.frame(
    Gene = diff_expr_matrix$Gene,  # This is incorrect because row.names will not exist.
    log2FoldChange = diff_expr_matrix$log2FoldChange,
    padj = diff_expr_matrix$padj
)

# The significantly differentially expressed genes are the ones found in the upper-left and upper-right corners.
# Add a column to the data frame to specify if they are UP- or DOWN- regulated (log2FoldChange respectively positive or negative)

# add a column of NAs
volcano_data$diffexpressed <- "Not significant"

# if log2Foldchange > 0 and pvalue < 0.1, set as "UP" 
volcano_data$diffexpressed[volcano_data$log2FoldChange > 0 & volcano_data$padj < 0.05] <- "UP"
# if log2Foldchange < -0.6 and pvalue < 0.05, set as "DOWN"
volcano_data$diffexpressed[volcano_data$log2FoldChange < -0 & volcano_data$padj < 0.05] <- "DOWN"
data_count_1 <- aggregate(data = volcano_data,                # Applying aggregate
                          Gene ~ diffexpressed,
                          function(x) length(unique(x)))
data_count_1  
# Re-plot but this time color the points with "diffexpressed"
p <- ggplot(data=volcano_data, aes(x=log2FoldChange, y=-log10(padj), col=diffexpressed)) + geom_point() + theme_bw()
p
## Change point color 
# 1. by default, it is assigned to the categories in an alphabetical order):
p1 <- p + scale_color_manual(values=c("brown4", "grey", "darkgreen"))
p1
ggsave("Pgrandis_Dur_Clad_volcano_plot.pdf", width = 4.5, height = 2.5)
```


```{r}
#start GOMWU
#notes when running GOMWU: the input data file should list all genes that were used in WGCNA; the genes that are not included in the module should receive a significance measure of 0, and genes within the module - a kME (correlation) values from WGCNA. If you are analysing signed WGCNA modules, add 'Module=TRUE,Alternative="g"' option when running gomwuStats(); for unsigned modules, just 'Module=TRUE' (see comments in the GO_MWU.R script).
```


```{r}
#annotations of genome can be found here:https://github.com/institut-de-genomique/TaraPacific_Pocillopora-transcriptomic/tree/main/Figure_4
goDatabase="go.obo"
goDivision="BP"
source("gomwu.functions.R")
goAnnotations="Pmean_GO.tab.txt"
#GOMWU analysis of Dur/Cla
#im gonna be using all dge files here.

dur_cla="Pgrandis_dge_Dur_gomwu.csv"
gomwuStats(dur_cla, goDatabase, goAnnotations, goDivision,
           perlPath="perl",
           largest=0.20,
           smallest=1,
           clusterCutHeight=0.25)


#removing redundancy:


```


```{r}

pdf("Pgrandis_DurvsClad_GOMWU_BP_v2.pdf", height = 3, width = 8)
gomwuPlot(dur_cla,goAnnotations,goDivision,
                  absValue=-log(0.05,10),  # genes with the measure value exceeding this will be counted as "good genes". This setting is for signed log-pvalues. Specify absValue=0.001 if you are doing Fisher's exact test for standard GO enrichment or analyzing a WGCNA module (all non-zero genes = "good genes").
                  #	absValue=1, # un-remark this if you are using log2-fold changes
                  level1=0.05, # FDR threshold for plotting. Specify level1=1 to plot all GO categories containing genes exceeding the absValue.
                  level2=0.01, # FDR cutoff to print in regular (not italic) font.
                  level3=0.001, # FDR cutoff to print in large bold font.
                  txtsize=1.5,    # decrease to fit more on one page, or increase (after rescaling the plot so the tree fits the text) for better "word cloud" effect
                  treeHeight=0.25, # height of the hierarchical clustering tree
                  colors=c("brown4","darkgreen","brown4","darkgreen") # these are default colors, un-remar and change if needed
)
dev.off()
```
